files:
  - source: /docs/
    ignore:
      - /**/kr/
      - /**/ru/
      - /**/cn/
      - /**/.vuepress/
      - '*.json'
    translation: /kr/%two_letters_code%/%original_path%/%original_file_name%
