files:
  - source: /docs/**/*.*
    ignore:
      - /docs/cn/
      - /docs/kr/
      - /docs/ru/
      - /.vuepress/
      - '*.json'
      - '*.jpg'
      - '*.png'
      - '*.sh'
    translation: /docs/%two_letters_code%/**/%original_file_name%
